// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTuSqcGi0BRZPCEHWye_6WzYFKK8W7eo',
    appId: '1:195449166114:web:4e840fe2a4c153748fad7b',
    messagingSenderId: '195449166114',
    projectId: 'socialmediaplatform-9c39a',
    authDomain: 'socialmediaplatform-9c39a.firebaseapp.com',
    databaseURL: 'https://socialmediaplatform-9c39a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaplatform-9c39a.appspot.com',
    measurementId: 'G-8JMTZQX96B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TebeJ4Vic4CfjB_9LQtYFaG30XMojMQ',
    appId: '1:195449166114:android:4e4bcce70e13fcf88fad7b',
    messagingSenderId: '195449166114',
    projectId: 'socialmediaplatform-9c39a',
    databaseURL: 'https://socialmediaplatform-9c39a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaplatform-9c39a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB28zKgt2LSnEICkMuZ3lBp6pzOemwUPC8',
    appId: '1:195449166114:ios:6584b4b94ff21d3c8fad7b',
    messagingSenderId: '195449166114',
    projectId: 'socialmediaplatform-9c39a',
    databaseURL: 'https://socialmediaplatform-9c39a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaplatform-9c39a.appspot.com',
    iosBundleId: 'com.example.socialmediaplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB28zKgt2LSnEICkMuZ3lBp6pzOemwUPC8',
    appId: '1:195449166114:ios:6584b4b94ff21d3c8fad7b',
    messagingSenderId: '195449166114',
    projectId: 'socialmediaplatform-9c39a',
    databaseURL: 'https://socialmediaplatform-9c39a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaplatform-9c39a.appspot.com',
    iosBundleId: 'com.example.socialmediaplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJTuSqcGi0BRZPCEHWye_6WzYFKK8W7eo',
    appId: '1:195449166114:web:109419f636c4211e8fad7b',
    messagingSenderId: '195449166114',
    projectId: 'socialmediaplatform-9c39a',
    authDomain: 'socialmediaplatform-9c39a.firebaseapp.com',
    databaseURL: 'https://socialmediaplatform-9c39a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaplatform-9c39a.appspot.com',
    measurementId: 'G-YL7QWB872W',
  );

}